name = "zero" 
main = "_worker.js"
compatibility_date = "2024-03-20"
compatibility_flags = [ "nodejs_compat" ]

# ✅ ဒီ line ကို ထည့်ပါ
keep_vars = true

[vars]
# UUID ကို ဒီမှာ မထည့်ထားဘူး (Dashboard မှာ ထည့်ထားမယ်)
PROXYIP = "cdn-b100.xn--b6gac.eu.org"
PROXY_LIST_URL = "https://galaxytunnel.github.io/PROXYIP.txt"
DNS_RESOLVER_URL = ["https://2mms0p4zud.cloudflare-gateway.com/dns-query",
  "https://dns.google/dns-query",
  "https://dns.quad9.net/dns-query"]
